spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: demo-service2
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
feign:
  hystrix:
    enabled: true
